/**
 * Export Module for WordStream
 * Provides functionality to export visualizations as PNG/SVG
 */

const ExportManager = {

    /**
     * Initialize export functionality
     */
    init: function() {
        this.addExportButton();
        console.log('✓ Export Manager initialized');
    },

    /**
     * Add export button to UI
     */
    addExportButton: function() {
        const menu = document.getElementById('menu');
        if (!menu) return;

        const buttonHTML = `
            <div class="control-section">
                <div class="control-section-title">💾 Export Visualization</div>
                <div class="export-btn-container">
                    <button id="exportPNGButton" class="export-btn-small" title="Export as PNG">
                        📥 PNG
                    </button>
                    <button id="exportSVGButton" class="export-btn-small" title="Export as SVG">
                        📥 SVG
                    </button>
                </div>
            </div>
        `;

        menu.insertAdjacentHTML('beforeend', buttonHTML);

        // Add event listeners
        const pngBtn = document.getElementById('exportPNGButton');
        const svgBtn = document.getElementById('exportSVGButton');

        if (pngBtn) pngBtn.addEventListener('click', () => this.exportPNG());
        if (svgBtn) svgBtn.addEventListener('click', () => this.exportSVG());

        // Add CSS
        this.addExportStyles();
    },

    /**
     * Add export button styles (now using control-panel.css)
     */
    addExportStyles: function() {
        // Styles are now in control-panel.css, no inline styles needed
        console.log('✓ Export styles loaded from control-panel.css');
    },

    /**
     * Export visualization as PNG
     */
    exportPNG: function() {
        const svg = document.getElementById('mainsvg');
        if (!svg) {
            alert('Visualization not found');
            return;
        }

        // Show exporting status
        const button = document.getElementById('exportPNGButton');
        const originalText = button.textContent;
        button.textContent = '⏳ Exporting...';
        button.disabled = true;

        try {
            // Get SVG data
            const svgData = new XMLSerializer().serializeToString(svg);
            const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
            const svgUrl = URL.createObjectURL(svgBlob);

            // Create canvas and draw
            const img = new Image();
            img.onload = () => {
                const canvas = document.createElement('canvas');
                canvas.width = svg.getAttribute('width');
                canvas.height = svg.getAttribute('height');

                const ctx = canvas.getContext('2d');

                // Draw white background
                ctx.fillStyle = 'white';
                ctx.fillRect(0, 0, canvas.width, canvas.height);

                // Draw image
                ctx.drawImage(img, 0, 0);

                // Add metadata text
                ctx.fillStyle = '#999';
                ctx.font = '10px Arial';
                ctx.fillText(`Generated by WordStream - ${new Date().toLocaleString()}`, 10, canvas.height - 5);

                // Export canvas to PNG
                canvas.toBlob((blob) => {
                    const pngUrl = URL.createObjectURL(blob);
                    const link = document.createElement('a');
                    link.href = pngUrl;
                    link.download = `wordstream-${Date.now()}.png`;
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);

                    // Cleanup
                    URL.revokeObjectURL(pngUrl);
                    URL.revokeObjectURL(svgUrl);

                    // Restore button
                    button.textContent = originalText;
                    button.disabled = false;
                }, 'image/png');
            };

            img.onerror = () => {
                alert('Error generating PNG. The visualization may be too complex.');
                button.textContent = originalText;
                button.disabled = false;
                URL.revokeObjectURL(svgUrl);
            };

            img.src = svgUrl;

        } catch (error) {
            console.error('Export error:', error);
            alert('Error exporting visualization: ' + error.message);
            button.textContent = originalText;
            button.disabled = false;
        }
    },

    /**
     * Export visualization as SVG
     */
    exportSVG: function() {
        const svg = document.getElementById('mainsvg');
        if (!svg) {
            alert('Visualization not found');
            return;
        }

        try {
            // Clone SVG
            const svgClone = svg.cloneNode(true);

            // Add metadata
            const metadata = document.createElementNS('http://www.w3.org/2000/svg', 'desc');
            metadata.textContent = `WordStream visualization exported on ${new Date().toLocaleString()}`;
            svgClone.insertBefore(metadata, svgClone.firstChild);

            // Serialize to string
            const svgData = new XMLSerializer().serializeToString(svgClone);

            // Add XML declaration and DOCTYPE
            const fullSvg = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
${svgData}`;

            // Create blob and download
            const blob = new Blob([fullSvg], { type: 'image/svg+xml;charset=utf-8' });
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = `wordstream-${Date.now()}.svg`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);

            // Cleanup
            URL.revokeObjectURL(url);

        } catch (error) {
            console.error('Export error:', error);
            alert('Error exporting SVG: ' + error.message);
        }
    },

    /**
     * Export data as JSON
     */
    exportJSON: function(data) {
        try {
            const jsonData = JSON.stringify(data, null, 2);
            const blob = new Blob([jsonData], { type: 'application/json;charset=utf-8' });
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = `wordstream-data-${Date.now()}.json`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);

            URL.revokeObjectURL(url);
            console.log('✓ Data exported as JSON');

        } catch (error) {
            console.error('Export error:', error);
            alert('Error exporting data: ' + error.message);
        }
    },

    /**
     * Copy visualization data to clipboard
     */
    copyToClipboard: function() {
        try {
            const svg = document.getElementById('mainsvg');
            const svgData = new XMLSerializer().serializeToString(svg);

            navigator.clipboard.writeText(svgData).then(() => {
                alert('SVG code copied to clipboard!');
            }).catch(err => {
                alert('Failed to copy: ' + err.message);
            });

        } catch (error) {
            console.error('Error:', error);
        }
    }
};

// Initialize on document ready
document.addEventListener('DOMContentLoaded', () => {
    ExportManager.init();
});
